### ISSUE TITLE
Fahrenheit support

### ISSUE THREAD

**Issue by bbrown430** [ghosty2004/homebridge-connectlife-ac#1]
**Describe The Bug:**
I am getting an error message that I believe is due to using Fahrenheit instead of Celsius. In the Homebridge web-ui, I am seeing the proper temperature, but in the iOS Home app, it is saying 153 degrees instead of 67 degrees. This makes it impossible to control, as that is outside of the range.

**To Reproduce:**

Use an A/C configured for Fahrenheit mode.

**Expected behavior:**

Proper temperature to show in the iOS Home app.

**Logs:**

```
[6/30/2024, 8:26:29 PM] [homebridge-connectlife-ac] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 67 exceeded maximum of 35. See https://homebridge.io/w/JtMGR for more info.
```

**Plugin Config:**

```json
{
    "name": "ConnectLife AC",
    "deviceNickName": "Air Conditioner",
    "loginID": "hiddn@gmail.com",
    "password": "hidden",
    "platform": "ConnectLifeAcPlugin"
}

**Environment:**

* **Plugin Version**: 1.2.1
* **Homebridge Version**: <!-- homebridge -V -->
* **Node.js Version**: v20.15.0
* **NPM Version**: <!-- npm -v -->
* **Operating System**: Debian GNU/Linux Bookworm (12)

**Comment by ghosty2004** [comment]
Hi.

Thanks for this issue report. I will take a look tomorrow to see what is wrong. If you have access to your ConnectLife app can you try to change the temperature unit to Celsius by navigating to `Your AC -> Settings -> Temperature Unit`.

After that, test it and then confirm if the issue is from here.

Thanks.

**Comment by bbrown430** [comment]
Awesome, 1.3.0 has fixed this. 

Not necessarily related to this issue, but I guess I'm confused about the expected behavior of the plugin in general.

The plugin reads the data fine, and whatever temperature I have the AC unit set to shows up in the Home app perfectly. However, it does not seem to be able to push data. When I set the AC to off in the home app, or adjust the temperature, nothing changes on my window AC unit. Furthermore, if I change the "Cool to" target, and then force close the app, that does not persist either.

Can you tell me what the expected behavior is for these actions?

**Comment by ghosty2004** [comment]
I tested only with split AC.
So you say you have a window AC and when you change the temperature from the HomeKit app it doesn't work?

The expected behavior is to work.

Maybe I will make a Debug option to output the logs from the external API server (from ConnectLife)

**Comment by bbrown430** [comment]
I'll open a new issue to keep this thread clean, and I'll share any additional details that could potentially help.
